spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/customer
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.type.mapping: customerCreated:com.bazan.carlend.kafka.CustomerCreated
server:
  port: 8090
